spring.application.name=GameOn
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/gameon
spring.datasource.username=root
spring.datasource.password=Vikhroli@83
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

